---

- name: Create/Update/Remove AWS Credential Secret
  jenkins_script:
    script: "{{ lookup('file', 'files/secret-scripts/aws-creds.groovy') }}"
    args: 
      secretId: "{{ item.key}}"
      secretState: "{{ item.value.state }}"
      accessKey: "{{ item.value.access_key | default('') }}"
      secretKey: "{{ item.value.secret_key | default('') }}"
      iamRoleArn: "{{ item.value.iam_role_arn | default('') }}"
    user: admin
    password: "{{ jenkins_admin_password }}" 
    url: "{{ jenkins_protocol }}://{{ jenkins_hostname }}:{{ jenkins_port }}"