---

- name: Create/Update/Remove Text Secret
  jenkins_script:
    script: "{{ lookup('file', 'files/secret-scripts/secret-text.groovy') }}"
    args: 
      secretId: "{{ item.key}}"
      secretState: "{{ item.value.state }}"
      secretText: "{{ item.value.secret_text }}"
    user: admin
    password: "{{ jenkins_admin_password }}" 
    url: "{{ jenkins_protocol }}://{{ jenkins_hostname }}:{{ jenkins_port }}"