---

- name: Create/Update/Remove SSH Secret
  jenkins_script:
    script: "{{ lookup('file', 'files/secret-scripts/ssh-key.groovy') }}"
    args: 
      secretId: "{{ item.key}}"
      sshUsername: "{{ item.value.ssh_username }}"
      sshKeyPath: "{{ item.value.ssh_key_location }}"
      secretState: "{{ item.value.state }}"
    user: admin
    password: "{{ jenkins_admin_password }}" 
    url: "{{ jenkins_protocol }}://{{ jenkins_hostname }}:{{ jenkins_port }}"