---

- name: Create/Update/Remove User/Password Secret
  jenkins_script:
    script: "{{ lookup('file', 'files/secret-scripts/user-password.groovy') }}"
    args: 
      secretId: "{{ item.key}}"
      secretState: "{{ item.value.state }}"
      username: "{{ item.value.username }}"
      pass: "{{ item.value.pass }}"
    user: admin
    password: "{{ jenkins_admin_password }}" 
    url: "{{ jenkins_protocol }}://{{ jenkins_hostname }}:{{ jenkins_port }}"