---

## Jenkins Install Tasks ##

- name: Get Jenkins Yum Repo Config
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    owner: root
    group: root
    mode: 0744

- name: Import Jenkins Yum Repo Key
  rpm_key:
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present

- name: Install Jenkins
  yum:
    name: jenkins
    state: present


