--- 

- name: Ssh key Jenkins Secret
  include: secrets/ssh-key-secret.yml
  static: no 
  when: item.value.secret_type == "ssh_key"

- name: User Password Jenkins Secret
  include: secrets/user-password-secret.yml
  static: no
  when: item.value.secret_type == "user_password"

- name: Secret File Jenkins Secret
  include: secrets/secret-file-secret.yml
  static: no
  when: item.value.secret_type == "secret_file"

- name: Secret Text Jenkins Secret 
  include: secrets/secret-text-secret.yml
  static: no
  when: item.value.secret_type == "secret_text"

- name: AWS Credential Secret
  include: secrets/aws-creds-secret.yml
  static: no
  when: item.value.secret_type == "aws_credential"

